### ISSUE TITLE
Revisar el estado del diagrama uml actual

### ISSUE THREAD

**Issue by AleSGXRD** [AleSGXRD/ProyectoDPOO#15]
Esta en fase de solo las clases y sus relaciones

**Comment by AleSGXRD** [comment]
Profe usted a revisado el uml de nosotros?

**Comment by yosbel-penate** [comment]
en eso estoy

**Comment by yosbel-penate** [comment]
hay dos digaramas, poner nombre a cada uno, ademas revisar la issue que les puse
